### ISSUE TITLE
Test `unload_on_kill_activate_as_group` fails on jazzy/testing

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_control#1753]
```
2024-09-13T02:29:16.7694364Z 9: /home/runner/work/ros2_control/ros2_control/.work/target_ws/src/ros2_control/controller_manager/test/test_spawner_unspawner.cpp:347: Failure
2024-09-13T02:29:16.7694540Z 9: Expected equality of these values:
2024-09-13T02:29:16.7694700Z 9:   cm_->get_loaded_controllers().size()
2024-09-13T02:29:16.7694790Z 9:     Which is: 2
2024-09-13T02:29:16.7694871Z 9:   0ul
2024-09-13T02:29:16.7694961Z 9:     Which is: 0
2024-09-13T02:29:16.7704118Z 9: 
```
see https://github.com/ros-controls/ros2_control/issues/1751

**Comment by christophfroehlich** [comment]
@saikishor could you have a look maybe?

**Comment by saikishor** [comment]
@christophfroehlich Is it failing more frequently?

**Comment by saikishor** [comment]
```
     [INFO] [1726194509.916911268] [spawner_ctrl_3]: [NON-XML-CHAR-0x1B][92mConfigured and activated all the parsed controllers list : ['ctrl_3', 'ctrl_2']![NON-XML-CHAR-0x1B][0m
    [INFO] [1726194509.917833389] [spawner_ctrl_3]: Waiting until interrupt to unload controllers
    /home/runner/work/ros2_control/ros2_control/.work/target_ws/src/ros2_control/controller_manager/test/test_spawner_unspawner.cpp:347: Failure
    Expected equality of these values:
      cm_->get_loaded_controllers().size()
        Which is: 2
      0ul
        Which is: 0
```

Seems like it didn't catch the keyboard interrupt. Let's wait to see if this happens more often.

Thank you!

**Comment by saikishor** [comment]
> Now and then, but at the next try it succeeded

Gotcha! We should keep an eye on this.

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control_ci/actions/runs/11227370628/job/31209485522

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control_ci/actions/runs/12554458549

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control_ci/issues/267

**Comment by christophfroehlich** [comment]
#2211

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/2238

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control_ci/issues/342

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control_ci/issues/355

**Comment by christophfroehlich** [comment]
#2322

**Comment by christophfroehlich** [comment]
#2320

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/2325

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control_ci/issues/378

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/2337

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/2392

**Comment by saikishor** [comment]
```
   Traceback (most recent call last):
      File "/home/runner/work/ros2_control/ros2_control/.work/target_ws/install/controller_manager/lib/python3.12/site-packages/controller_manager/spawner.py", line 352, in main
        time.sleep(1)
    KeyboardInterrupt
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/usr/lib/python3/dist-packages/coverage/__main__.py", line 10, in <module>
        sys.exit(main())
                 ^^^^^^
      File "/usr/lib/python3/dist-packages/coverage/cmdline.py", line 970, in main
        status = CoverageScript().command_line(argv)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/coverage/cmdline.py", line 681, in command_line
        return self.do_run(options, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/coverage/cmdline.py", line 858, in do_run
        runner.run()
      File "/usr/lib/python3/dist-packages/coverage/execfile.py", line 211, in run
        exec(code, main_mod.__dict__)
      File "/home/runner/work/ros2_control/ros2_control/.work/target_ws/install/controller_manager/lib/controller_manager/spawner", line 33, in <module>
        sys.exit(load_entry_point('controller-manager==4.33.0', 'console_scripts', 'spawner')())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/work/ros2_control/ros2_control/.work/target_ws/install/controller_manager/lib/python3.12/site-packages/controller_manager/spawner.py", line 355, in main
        logger.info("KeyboardInterrupt successfully captured!")
      File "/opt/ros/jazzy/lib/python3.12/site-packages/rclpy/impl/rcutils_logger.py", line 341, in info
        def info(self, message, **kwargs):
    
    KeyboardInterrupt
    /home/runner/work/ros2_control/ros2_control/.work/target_ws/src/ros2_control/controller_manager/test/test_spawner_unspawner.cpp:601: Failure
    Expected equality of these values:
      cm_->get_loaded_controllers().size()
        Which is: 2
      0ul
        Which is: 0
    
    [INFO] [1752550945.715375762] [test_controller_manager.pal_statistics]: Async messages lost 0
    [INFO] [1752550945.715406460] [test_controller_manager.pal_statistics]: publish_async_failures_ 0
```

It seems like the second exception is partly from the coverage script

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/2397
but this is not a coverage build?

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/2438

**Comment by saikishor** [comment]
```
     Traceback (most recent call last):
      File "/__w/ros2_control/ros2_control/install/controller_manager/lib/python3.11/site-packages/controller_manager/spawner.py", line 333, in main
        time.sleep(1)
    KeyboardInterrupt
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/usr/lib/python3/dist-packages/coverage/__main__.py", line 8, in <module>
        sys.exit(main())
                 ^^^^^^
      File "/usr/lib/python3/dist-packages/coverage/cmdline.py", line 943, in main
        status = CoverageScript().command_line(argv)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/coverage/cmdline.py", line 659, in command_line
        return self.do_run(options, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/coverage/cmdline.py", line 830, in do_run
        runner.run()
      File "/usr/lib/python3/dist-packages/coverage/execfile.py", line 199, in run
        exec(code, main_mod.__dict__)
      File "/__w/ros2_control/ros2_control/install/controller_manager/lib/controller_manager/spawner", line 33, in <module>
        sys.exit(load_entry_point('controller-manager==5.6.0', 'console_scripts', 'spawner')())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/__w/ros2_control/ros2_control/install/controller_manager/lib/python3.11/site-packages/controller_manager/spawner.py", line 336, in main
        logger.info("KeyboardInterrupt successfully captured!")
      File "/opt/ros2_ws/install/rclpy/lib/python3.11/site-packages/rclpy/impl/rcutils_logger.py", line 418, in info
        def info(self, message: str, **kwargs: 'Unpack[LoggingArgs]') -> bool:
    
    KeyboardInterrupt
    /__w/ros2_control/ros2_control/src/ros-controls/ros2_control/controller_manager/test/test_spawner_unspawner.cpp:601: Failure
    Expected equality of these values:
      cm_->get_loaded_controllers().size()
        Which is: 2
      0ul
        Which is: 0
```

The same happened today https://github.com/ros-controls/ros2_control/actions/runs/17912528079/job/50927116415?pr=2557

Why is the coverage/cmdline.py catching the exception too. I don't know this one. I tried locally but couldn't reproduce it

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/actions/runs/18991010496/job/54243979686?pr=2765
jazzy/RHEL

```
     [  FAILED  ] TestLoadController.unload_on_kill_activate_as_group
    
     1 FAILED TEST
    -- run_test.py: return code 1
    -- run_test.py: inject classname prefix into gtest result file '/__w/ros2_control/ros2_control/build/controller_manager/test_results/controller_manager/test_spawner_unspawner.gtest.xml'
    -- run_test.py: verify result file '/__w/ros2_control/ros2_control/build/controller_manager/test_results/controller_manager/test_spawner_unspawner.gtest.xml'
  >>>
build/controller_manager/test_results/controller_manager/test_spawner_unspawner.gtest.xml: 26 tests, 0 errors, 1 failure, 0 skipped
- controller_manager.TestLoadController unload_on_kill_activate_as_group (/__w/ros2_control/ros2_control/src/ros-controls/ros2_control/controller_manager/test/test_spawner_unspawner.cpp:585)
  <<< failure message
    /__w/ros2_control/ros2_control/src/ros-controls/ros2_control/controller_manager/test/test_spawner_unspawner.cpp:601
    Expected equality of these values:
      cm_->get_loaded_controllers().size()
        Which is: 2
      0ul
        Which is: 0
  >>>
```

**Comment by christophfroehlich** [comment]
rolling/testing
https://github.com/ros-controls/ros2_control/issues/2810

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/2864

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/2883

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/2901

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/2920

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control_ci/issues/608

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/3074

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control_ci/issues/806

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control/issues/3339
