### ISSUE TITLE
Issue building from source.

### ISSUE THREAD

**Issue by wglockner** [ros-controls/ros2_control#1804]
**Description of problem**
I need to build the Humble branch from source.  I cloned the repo into my ros2 workspace, cloned the ros2_control.humble.repos repos, and built using colcon build.  The build failed.

**To Reproduce**
1. cd <workspace_root>
2. cd src
3. git clone https://github.com/ros-controls/ros2_control.git
4. cd ros2_control/
5. git checkout humble 
6. source /opt/ros/humble/setup.bash
7. rosdep update
8. vcs import --shallow --debug src/ros2_control < src/ros2_control/ros2_control.humble.repos
9. (also tried) vcs import --shallow --debug src < src/ros2_control/ros2_control.humble.repos
10. rosdep install --from-paths src --ignore-src -r -y
11. colcon build

**Expected behavior**
Workspace builds and lists all packages build successfully.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 Jammy Jellyfish
 - Version Humble

**Additional context**
```bash
~/Desktop/rs/hum_driv$ colcon build
Starting >>> control_msgs
Starting >>> ros2_control_test_assets
Starting >>> controller_manager_msgs
Starting >>> realtime_tools
Starting >>> joint_limits
Finished <<< ros2_control_test_assets [0.07s]
Finished <<< joint_limits [0.10s]                                                                        
--- stderr: controller_manager_msgs                                                                      
CMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
  execute_process(/home/xxxxxx/.pyenv/versions/3.11.0/bin/python3 -m
  rosidl_adapter --package-name controller_manager_msgs --arguments-file
  /home/xxxxxx/Desktop/rs/hum_driv/build/controller_manager_msgs/rosidl_adapter__arguments__controller_manager_msgs.json
  --output-dir
  /home/xxxxxx/Desktop/rs/hum_driv/build/controller_manager_msgs/rosidl_adapter/controller_manager_msgs
  --output-file
  /home/xxxxxx/Desktop/rs/hum_driv/build/controller_manager_msgs/rosidl_adapter/controller_manager_msgs.idls)
  returned error code 1:

  AttributeError processing template 'msg.idl.em'

  Traceback (most recent call last):

    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 51, in evaluate_template
      em.BUFFERED_OPT: True,
      ^^^^^^^^^^^^^^^

  AttributeError: module 'em' has no attribute 'BUFFERED_OPT'



  During handling of the above exception, another exception occurred:



  Traceback (most recent call last):

    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
               ^^^^^^
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
                     ^^^^^^^^^^^^^^^
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
             ^^^^^^^^^^^^^^^^^^^
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 39, in convert_msg_to_idl
      expand_template('msg.idl.em', data, output_file, encoding='iso-8859-1')
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 23, in expand_template
      content = evaluate_template(template_name, data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 69, in evaluate_template
      _interpreter.shutdown()
      ^^^^^^^^^^^^^^^^^^^^^

  AttributeError: 'NoneType' object has no attribute 'shutdown'

Call Stack (most recent call first):
  /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:32 (rosidl_generate_interfaces)


---
Failed   <<< controller_manager_msgs [0.36s, exited with code 1]
Aborted  <<< control_msgs [0.39s]
Aborted  <<< realtime_tools [7.52s]                                 

Summary: 2 packages finished [7.67s]
  1 package failed: controller_manager_msgs
  2 packages aborted: control_msgs realtime_tools
  2 packages had stderr output: control_msgs controller_manager_msgs
  8 packages not processed
```

**Comment by christophfroehlich** [comment]
This is not related to ros2_control, see https://github.com/ros2/rosidl/issues/779
