### ISSUE TITLE
Wildcard nodes in parameter file not supported by controller spawner

### ISSUE THREAD

**Issue by bijoua29** [ros-controls/ros2_control#1932]
**Describe the bug**
If the parameter file passed to controller spawner only has wildcard node parameters, spawner fails

**To Reproduce**
1. Start controller passing in parameter file to controller spawner with only wildcard node parameter. For example,

```python
load_controller = [
            ExecuteProcess(
                cmd=[
                    "ros2 run controller_manager spawner my_controller "
                    + "--param-file my_controller_params.yaml "
                    + "--controller-manager-timeout 50 "
                    + f"--ros-args --log-level {log_level} --log-file-name my_controller_spawner"
                ],
                name=my_controller_spawner,
                shell=True,
                output=both",
            )
        ]
```
        
        
 my_controller_params.yaml example:
 
```yaml
 /**:
  ros__parameters:
    param1: 1.0
    param2: 2.0
```
    
2. See error like following:

```
[my_controller_spawner-12] [FATAL] [1733946036.807125471] [spawner_my_controller]: Controller : /my_controller parameters not found in parameter file : /home/user/workspace/my_ws/install/app_bringup/share/app_bringup/config/my_controller_params.yaml
[my_controller_spawner-12] Traceback (most recent call last):
[my_controller_spawner-12]   File "/home/user/workspace/my_ws/install/controller_manager/lib/controller_manager/spawner", line 33, in <module>
[my_controller_spawner-12]     sys.exit(load_entry_point('controller-manager==4.20.0', 'console_scripts', 'spawner')())
[my_controller_spawner-12]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[my_controller_spawner-12]   File "/home/user/workspace/my_ws/install/controller_manager/lib/python3.12/site-packages/controller_manager/spawner.py", line 176, in main
[my_controller_spawner-12]     if not set_controller_parameters_from_param_file(
[my_controller_spawner-12]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[my_controller_spawner-12]   File "/home/user/workspace/my_ws/install/controller_manager/lib/python3.12/site-packages/controller_manager/controller_manager_services.py", line 359, in set_controller_parameters_from_param_file
[my_controller_spawner-12]     controller_type = get_parameter_from_param_file(
[my_controller_spawner-12]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[my_controller_spawner-12]   File "/home/user/workspace/my_ws/install/controller_manager/lib/python3.12/site-packages/controller_manager/controller_manager_services.py", line 303, in get_parameter_from_param_file
[my_controller_spawner-12]     if parameter_name in controller_param_dict[ROS_PARAMS_KEY]:
[my_controller_spawner-12]                          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
[my_controller_spawner-12] TypeError: 'NoneType' object is not subscriptable
[ERROR] [my_controller_spawner-12]: process has died [pid 62480, exit code 1, cmd 'ros2 run controller_manager spawner my_controller --param-file /home/user/workspace/my_ws/install/app_bringup/share/app_bringup/config/my_controller_params.yaml --controller-manager-timeout 40 --ros-args --log-level ERROR --log-file-name my_controller_spawner'].
```

**Expected behavior**
Controller should start with spawner without any errors

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04
 - Version: rolling sync as of 2024-11-26
 - ros2_control Version: 4.20.0

**Additional context**
Controller starts fine if I have the controller name instead of wildcard. However, I want to use the parameter file with wildcard since I have several instances of this controller and I want to use the same parameter file.

I also tried a test with controller manager parameter lock_memory set to false and it had no change in behavior.

I can't create a minimal reproducible example as my controller is proprietary code and has other dependencies.

**Comment by christophfroehlich** [comment]
Can you reproduce this with any of the ros2_control_demos?

**Comment by saikishor** [comment]
Hello @bijoua29!

**Comment by saikishor** [comment]
Hello @bijoua29!

I provided a fix to your issue in #1933. It would be great if you can test it and let us know if it works. If it works as you expect, I would appreciate approval to the PR.

Thank you!

**Comment by bijoua29** [comment]
The fix works great. I have approved it. Can close this issue out when the PR is merged upstream
