### ISSUE TITLE
ros2ci foxy source job failing on master

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#214]
I couldn't reproduce the issue, it seems that there's a failure with taking down the launch test.

here's the relevant snippet from https://github.com/ros-controls/ros2_control/pull/209/checks?check_run_id=1313191689
```
2020-10-27T07:04:10.5108897Z [0.689s] 2: [joint_limits_rosparam_test-1] [==========] Running 2 tests from 1 test case.
2020-10-27T07:04:10.5109709Z [0.689s] 2: [joint_limits_rosparam_test-1] [----------] Global test environment set-up.
2020-10-27T07:04:10.5110642Z [0.689s] 2: [joint_limits_rosparam_test-1] [----------] 2 tests from JointLimitsRosParamTest
2020-10-27T07:04:10.5111886Z [0.690s] 2: [joint_limits_rosparam_test-1] [ RUN      ] JointLimitsRosParamTest.GetJointLimits
2020-10-27T07:04:10.5114021Z [0.690s] 2: [joint_limits_rosparam_test-1] [ERROR] [1603782246.659434414] [JointLimitsRosparamTestNode]: No joint limits specification found for joint 'bad_joint' in the parameter server (node: JointLimitsRosparamTestNode param name: joint_limits.bad_joint).
2020-10-27T07:04:10.5116674Z [0.690s] 2: [joint_limits_rosparam_test-1] [ERROR] [1603782246.659543314] [JointLimitsRosparamTestNode]: No joint limits specification found for joint 'unknown_joint' in the parameter server (node: JointLimitsRosparamTestNode param name: joint_limits.unknown_joint).
2020-10-27T07:04:10.5118746Z [0.700s] 2: [joint_limits_rosparam_test-1] [       OK ] JointLimitsRosParamTest.GetJointLimits (24 ms)
2020-10-27T07:04:10.5120246Z [0.701s] 2: [joint_limits_rosparam_test-1] [ RUN      ] JointLimitsRosParamTest.GetSoftJointLimits
2020-10-27T07:04:10.5122002Z [0.705s] 2: [joint_limits_rosparam_test-1] [       OK ] JointLimitsRosParamTest.GetSoftJointLimits (5 ms)
2020-10-27T07:04:10.5123576Z [0.705s] 2: [joint_limits_rosparam_test-1] [----------] 2 tests from JointLimitsRosParamTest (29 ms total)
2020-10-27T07:04:10.5124389Z [0.705s] 2: [joint_limits_rosparam_test-1] 
2020-10-27T07:04:10.5125119Z [0.706s] 2: [joint_limits_rosparam_test-1] [----------] Global test environment tear-down
2020-10-27T07:04:10.5126069Z [0.706s] 2: [joint_limits_rosparam_test-1] [==========] 2 tests from 1 test case ran. (29 ms total)
2020-10-27T07:04:10.5126860Z [0.706s] 2: [joint_limits_rosparam_test-1] [  PASSED  ] 2 tests.
2020-10-27T07:04:10.5127660Z [0.709s] 2: [INFO] [joint_limits_rosparam_test-1]: process has finished cleanly [pid 25372]
2020-10-27T07:04:10.5128488Z [0.711s] 2: [INFO] [python3-2]: sending signal 'SIGINT' to process[python3-2]
2020-10-27T07:04:10.5129340Z [0.711s] 2: [python3-2] Fatal Python error: init_import_size: Failed to import the site module
2020-10-27T07:04:10.5130157Z [0.712s] 2: [python3-2] Python runtime state: initialized
2020-10-27T07:04:10.5130823Z [0.746s] 2: [python3-2] Traceback (most recent call last):
2020-10-27T07:04:10.5131674Z [0.746s] 2: [python3-2]   File "/usr/lib/python3.8/site.py", line 79, in <module>
2020-10-27T07:04:10.5132334Z [0.747s] 2: [python3-2]     import os
2020-10-27T07:04:10.5133021Z [0.747s] 2: [python3-2]   File "/usr/lib/python3.8/os.py", line 59, in <module>
2020-10-27T07:04:10.5133744Z [0.748s] 2: [python3-2]     import posixpath as path
2020-10-27T07:04:10.5134553Z [0.748s] 2: [python3-2]   File "/usr/lib/python3.8/posixpath.py", line 28, in <module>
2020-10-27T07:04:10.5135295Z [0.749s] 2: [python3-2]     import genericpath
2020-10-27T07:04:10.5136079Z [0.749s] 2: [python3-2]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-10-27T07:04:10.5137010Z [0.749s] 2: [python3-2]   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-10-27T07:04:10.5137961Z [0.750s] 2: [python3-2]   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-10-27T07:04:10.5138842Z [0.750s] 2: [python3-2]   File "<frozen importlib._bootstrap_external>", line 779, in exec_module
2020-10-27T07:04:10.5139783Z [0.751s] 2: [python3-2]   File "<frozen importlib._bootstrap_external>", line 911, in get_code
2020-10-27T07:04:10.5140760Z [0.751s] 2: [python3-2]   File "<frozen importlib._bootstrap_external>", line 580, in _compile_bytecode
2020-10-27T07:04:10.5141589Z [0.752s] 2: [python3-2] KeyboardInterrupt
2020-10-27T07:04:10.5142431Z [0.752s] 2: [ERROR] [python3-2]: process has died [pid 25375, exit code 1, cmd '/usr/bin/python3 -c 
2020-10-27T07:04:10.5142908Z [0.752s] 2: try:
2020-10-27T07:04:10.5143218Z [0.752s] 2:     while True:
2020-10-27T07:04:10.5143522Z [0.752s] 2:         pass
2020-10-27T07:04:10.5143948Z [0.752s] 2: except KeyboardInterrupt:
2020-10-27T07:04:10.5144297Z [0.752s] 2:     pass
2020-10-27T07:04:10.5144703Z [0.753s] 2: '].
2020-10-27T07:04:10.5144970Z [0.753s] 2: ok
2020-10-27T07:04:10.5145250Z [0.753s] 2: 
2020-10-27T07:04:10.5145727Z [0.754s] 2: ----------------------------------------------------------------------
2020-10-27T07:04:10.5146047Z [0.754s] 2: Ran 1 test in 0.046s
2020-10-27T07:04:10.5146338Z [0.754s] 2: 
2020-10-27T07:04:10.5146544Z [0.754s] 2: OK
2020-10-27T07:04:10.5147735Z [0.755s] 2: test_exit_code (joint_limits_interface.TestJointLimitInterfaceTestAfterShutdown) ... FAIL
```

while when I locally run the same, I get this
```
$ launch_test src/ros2_control/joint_limits_interface/test/joint_limits_rosparam.launch.py 
[INFO] [launch]: All log files can be found below /home/bence/.ros/log/2020-10-27-07-27-19-181182-blackbrick-297797
[INFO] [launch]: Default logging verbosity is set to INFO
test_termination (joint_limits_rosparam.launch.TestJointLimitInterface) ... [INFO] [joint_limits_rosparam_test-1]: process started with pid [297800]
[INFO] [python3-2]: process started with pid [297802]
[joint_limits_rosparam_test-1] [==========] Running 2 tests from 1 test case.
[joint_limits_rosparam_test-1] [----------] Global test environment set-up.
[joint_limits_rosparam_test-1] [----------] 2 tests from JointLimitsRosParamTest
[joint_limits_rosparam_test-1] [ RUN      ] JointLimitsRosParamTest.GetJointLimits
[joint_limits_rosparam_test-1] [ERROR] [1603783639.205507749] [JointLimitsRosparamTestNode]: No joint limits specification found for joint 'bad_joint' in the parameter server (node: JointLimitsRosparamTestNode param name: joint_limits.bad_joint).
[joint_limits_rosparam_test-1] [ERROR] [1603783639.205618005] [JointLimitsRosparamTestNode]: No joint limits specification found for joint 'unknown_joint' in the parameter server (node: JointLimitsRosparamTestNode param name: joint_limits.unknown_joint).
[joint_limits_rosparam_test-1] [       OK ] JointLimitsRosParamTest.GetJointLimits (10 ms)
[joint_limits_rosparam_test-1] [ RUN      ] JointLimitsRosParamTest.GetSoftJointLimits
[joint_limits_rosparam_test-1] [       OK ] JointLimitsRosParamTest.GetSoftJointLimits (4 ms)
[joint_limits_rosparam_test-1] [----------] 2 tests from JointLimitsRosParamTest (14 ms total)
[joint_limits_rosparam_test-1] 
[joint_limits_rosparam_test-1] [----------] Global test environment tear-down
[joint_limits_rosparam_test-1] [==========] 2 tests from 1 test case ran. (14 ms total)
[joint_limits_rosparam_test-1] [  PASSED  ] 2 tests.
[INFO] [joint_limits_rosparam_test-1]: process has finished cleanly [pid 297800]
ok

----------------------------------------------------------------------
Ran 1 test in 0.028s

OK
[INFO] [python3-2]: sending signal 'SIGINT' to process[python3-2]
[INFO] [python3-2]: process has finished cleanly [pid 297802]
test_exit_code (joint_limits_rosparam.launch.TestJointLimitInterfaceTestAfterShutdown) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

@piraka9011 @Karsten1987 do you guys have any clue why we'd be seeing this? Anyone worth contacting? 
```

**Comment by bmagyar** [comment]
Fixed via updates
