### ISSUE TITLE
race condition in spawner

### ISSUE THREAD

**Issue by tylerjw** [ros-controls/ros2_control#682]
**Describe the bug**
In spawner.py the function `wait_for_controller_manager` waits for the node name to exist. Immediately after it is called `is_controller_loaded` is called which calls `list_controllers`.  `list_controlers` depends on the service `/controller_manager/list_controllers` to be available. Even though the log message in `wait_for_controller_manager` says it is waiting for services, that is not actually what is doing. I am not sure how to make a minimal example of this race condition but in my current setup, this consistently causes the spawner to crash with a `RuntimeError`. I'm happy to try to help resolve this.

```
[spawner-3] Traceback (most recent call last):
[spawner-3]   File "/opt/ros/galactic/lib/controller_manager/spawner", line 20, in <module>
[spawner-3]     ret = main()
[spawner-3]   File "/opt/ros/galactic/lib/controller_manager/spawner.py", line 123, in main
[spawner-3]     if is_controller_loaded(node, controller_manager_name, controller_name):
[spawner-3]   File "/opt/ros/galactic/lib/controller_manager/spawner.py", line 66, in is_controller_loaded
[spawner-3]     controllers = list_controllers(node, controller_manager).controller
[spawner-3]   File "/opt/ros/galactic/lib/python3.8/site-packages/controller_manager/controller_manager_services.py", line 49, in list_controllers
[spawner-3]     return service_caller(node, f'{controller_manager_name}/list_controllers',
[spawner-3]   File "/opt/ros/galactic/lib/python3.8/site-packages/controller_manager/controller_manager_services.py", line 29, in service_caller
[spawner-3]     raise RuntimeError(f'Could not contact service {service_name}')
[spawner-3] RuntimeError: Could not contact service /controller_manager/list_controllers
```

**Expected behavior**
Spawner waits for the controller_manager services to exist before trying to contact them.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version Galactic from Debians

```
Package: ros-galactic-controller-manager
Version: 1.4.0-1focal.20220218.095121
Priority: optional
Section: misc
Maintainer: karsten <karsten@osrfoundation.org>
Installed-Size: 1,119 kB
Depends: libc6 (>= 2.14), libgcc-s1 (>= 3.0), libstdc++6 (>= 6), libtinyxml2-6a (>= 5.0.0), ros-galactic-console-bridge-vendor, ros-galactic-ament-index-cpp, ros-galactic-controller-interface, ros-galactic-controller-manager-msgs, ros-galactic-hardware-interface, ros-galactic-launch, ros-galactic-launch-ros, ros-galactic-pluginlib, ros-galactic-rclcpp, ros-galactic-rcpputils, ros-galactic-ros2-control-test-assets, ros-galactic-ros2param, ros-galactic-ros2run, ros-galactic-ros-workspace
Download-Size: 191 kB
APT-Sources: http://packages.ros.org/ros2/ubuntu focal/main amd64 Packages
Description: Description of controller_manager
```

**Comment by tylerjw** [comment]
I found this function that might provide a way to wait for the interfaces of the controller_manager to be up first: https://docs.ros2.org/latest/api/rclpy/api/node.html#rclpy.node.Node.get_client_names_and_types_by_node

Is there a list of the required set of ros interfaces of controller_manager somewhere I can reference?
