### ISSUE TITLE
Error in state! Internal state_handle is NULL.

### ISSUE THREAD

**Issue by muttistefano** [ros-controls/ros2_control#860]
Ubuntu 22.04 , Rolling
Just updated ros2_control from the rolling repository and now doesn't work anymore

The error is :

```
[ros2_control_node-1] terminate called after throwing an instance of 'std::runtime_error'   
[ros2_control_node-1]   what():  Error in state! Internal state_handle is NULL.   
[ERROR] [ros2_control_node-1]: process has died [pid 142785, exit code -6, cmd '/opt/ros/rolling/lib/controller_manager/ros2_control_node --ros-args --params-file /tmp/launch_params_3eb4uscc --params-file /home/blanker/omron/install/ur_hardware_interface/share/ur_hardware_interface/config/ur10_update_rate.yaml --params-file /home/blanker/omron/install/ur_hardware_interface/share/ur_hardware_interface/config/ur_controllers.yaml'].
```

Gdb shows : 
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737341792064) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737341792064) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737341792064, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7857476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff783d7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7b01bbe in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7b0d24c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7b0d2b7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7b0d518 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff76deb1a in ?? () from /opt/ros/rolling/lib/librclcpp_lifecycle.so
#10 0x00007ffff77d4208 in hardware_interface::System::initialize(hardware_interface::HardwareInfo const&) () from /opt/ros/rolling/lib/libhardware_interface.so
#11 0x00007ffff77dd78c in ?? () from /opt/ros/rolling/lib/libhardware_interface.so
#12 0x00007ffff77ba3fb in hardware_interface::ResourceManager::load_urdf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
   from /opt/ros/rolling/lib/libhardware_interface.so
#13 0x00007ffff7f26d4e in controller_manager::ControllerManager::init_resource_manager(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /opt/ros/rolling/lib/libcontroller_manager.so
#14 0x00007ffff7f27cb1 in controller_manager::ControllerManager::ControllerManager(std::shared_ptr<rclcpp::Executor>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /opt/ros/rolling/lib/libcontroller_manager.so
#15 0x0000555555556866 in ?? ()
#16 0x00007ffff783ed90 in __libc_start_call_main (main=main@entry=0x5555555566f0, argc=argc@entry=8, argv=argv@entry=0x7fffffffc4c8) at ../sysdeps/nptl/libc_start_call_main.h:58
#17 0x00007ffff783ee40 in __libc_start_main_impl (main=0x5555555566f0, argc=8, argv=0x7fffffffc4c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffc4b8)
    at ../csu/libc-start.c:392
#18 0x0000555555556d35 in ?? ()
```

Is someone experiencing the same error ? 
Thanks

**Comment by muttistefano** [comment]
Cleaning and building the workspace fixed it
